import Instagram from "@/components/Instagram"
import Head from "next/head"
import Image from "next/image"
import Hero from "../components/Hero"
import Slider from "../components/Slider"
import { SliderData } from "../components/SliderData"

export default function Home() {
    return (
        <div>
            <Head>
                <title>AI Choom pictures</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero heading="AI pics" message="AI is cooperating with cooperative devs." />
            <Slider slides={SliderData} />
            <Instagram />
        </div>
    )
}
